# Generated by Django 4.2.11 on 2024-05-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=40, unique=True)),
                ('pwd', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('birth', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=300, unique=True)),
            ],
        ),
    ]
