# Generated by Django 4.2.11 on 2024-05-30 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_alter_imageupload_img_alter_imageupload_img_caption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageupload',
            options={'verbose_name': '이미지 업로드', 'verbose_name_plural': '이미지 업로드'},
        ),
        migrations.AddField(
            model_name='imageupload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterModelTable(
            name='imageupload',
            table='imageUpload',
        ),
    ]
