# Generated by Django 4.2.11 on 2024-06-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_imageupload_options_imageupload_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='img',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='img_caption',
        ),
    ]
